// Auto-generated from gimmicks.txt (EWR native IDs)
export type Gimmick = { id: number; name: string };
export const GIMMICKS: Gimmick[] = [
  { id: 0, name: "None" },
  { id: 1, name: "Savage" },
  { id: 2, name: "Cocky" },
  { id: 3, name: "Cowardly" },
  { id: 4, name: "Bad Ass" },
  { id: 5, name: "Hero" },
  { id: 6, name: "Psycho" },
  { id: 7, name: "Mysterious" },
  { id: 8, name: "Evil" },
  { id: 9, name: "Legitimate Athlete" },
  { id: 10, name: "Daredevil" },
  { id: 11, name: "Prima Donna" },
  { id: 12, name: "Teen Idol" },
  { id: 13, name: "High Society" },
  { id: 14, name: "Underdog" },
  { id: 15, name: "Egomaniac" },
  { id: 16, name: "Cool" },
  { id: 17, name: "Gangsta" },
  { id: 18, name: "Crazy" },
  { id: 19, name: "Comedy Character" },
  { id: 20, name: "Dude" },
  { id: 21, name: "Freak" },
  { id: 22, name: "Obnoxious" },
  { id: 23, name: "Cheater" },
  { id: 24, name: "Monster" },
  { id: 25, name: "Evil Foreigner" },
  { id: 26, name: "Fun Babyface" },
  { id: 27, name: "Seductress" },
  { id: 28, name: "Bitch" },
  { id: 29, name: "Girl-Next-Door" },
  { id: 30, name: "Evil Boss" },
  { id: 31, name: "Gay" },
  { id: 32, name: "Suave" },
  { id: 33, name: "Tomboy" },
  { id: 34, name: "Troublemaker" },
  { id: 35, name: "Foreign Star" },
  { id: 36, name: "Degenerate" },
  { id: 37, name: "Authority Figure" },
  { id: 38, name: "Weirdo" },
  { id: 39, name: "Loner" },
  { id: 40, name: "Genius" },
  { id: 41, name: "Lackey" },
  { id: 42, name: "No Gimmick Needed" },
  { id: 43, name: "Cowboy" },
  { id: 44, name: "Redneck" },
  { id: 45, name: "Pro USA" },
  { id: 46, name: "Anti USA" },
  { id: 47, name: "Underworld" },
  { id: 48, name: "Slut" },
  { id: 49, name: "Rich Snob" },
  { id: 50, name: "Inspirational Leader" },
  { id: 51, name: "Native American" },
  { id: 52, name: "Slob" },
  { id: 53, name: "Chosen One" },
  { id: 54, name: "Blue Chipper" },
  { id: 55, name: "Power and Paint" },
  { id: 56, name: "Punk" },
  { id: 57, name: "Franchise Player" },
  { id: 58, name: "Extremist" },
  { id: 59, name: "Old School Heel" },
  { id: 60, name: "Old School Face" },
  { id: 61, name: "Blue Collar" },
  { id: 62, name: "Gothic" },
  { id: 63, name: "Cheerleader" },
  { id: 64, name: "Trash" },
  { id: 65, name: "BFG" },
  { id: 66, name: "Unique" },
  { id: 67, name: "Occult" },
  { id: 68, name: "Putz" },
  { id: 69, name: "Rapper" },
  { id: 70, name: "Hired Gun" },
  { id: 71, name: "Arrogant" },
  { id: 72, name: "Ravishing" },
  { id: 73, name: "Armed Forces" },
  { id: 74, name: "Supernatural" },
  { id: 75, name: "Geek" },
  { id: 76, name: "Bounty Hunter" },
  { id: 77, name: "Mentor" },
  { id: 78, name: "Ninja" },
  { id: 79, name: "Martial Arts" },
  { id: 80, name: "Bodyguard" },
  { id: 81, name: "Angry Young Man" },
  { id: 82, name: "Rebel" },
  { id: 83, name: "Man on a Mission" },
  { id: 84, name: "Executive Consultant" },
  { id: 85, name: "Coach" },
  { id: 86, name: "The Brain" },
  { id: 87, name: "Man in Black" },
  { id: 88, name: "Glam Rocker" },
  { id: 89, name: "Gender Bender" },
  { id: 90, name: "Metalhead" },
  { id: 91, name: "Grunge" },
  { id: 92, name: "Detective" },
  { id: 93, name: "Junkie" },
  { id: 94, name: "Dealer" },
  { id: 95, name: "Theif" },
  { id: 96, name: "Journalist" },
  { id: 97, name: "Comedian" },
  { id: 98, name: "Pacifist" },
  { id: 99, name: "Unlucky" },
  { id: 100, name: "Chameleon" },
  { id: 101, name: "Comic Book Hero" },
  { id: 102, name: "Comic Book Villian" },
  { id: 103, name: "Evil Preacher" },
  { id: 104, name: "Bumbling Englishman" },
  { id: 105, name: "Fun Drunk" },
  { id: 106, name: "Violent Drunk" },
  { id: 107, name: "Lumberjack" },
  { id: 108, name: "Stoner" },
  { id: 109, name: "Outbacker" },
  { id: 110, name: "Comrade" },
  { id: 111, name: "Arabian" },
  { id: 112, name: "Sidekick" },
  { id: 113, name: "Braveheart" },
  { id: 114, name: "Movie Star" },
  { id: 115, name: "Enforcer" },
  { id: 116, name: "Censor" },
  { id: 117, name: "Split Personality" },
  { id: 118, name: "Highlight Reel" },
  { id: 119, name: "Machine" },
  { id: 120, name: "Demon" },
  { id: 121, name: "Imperssionist" },
  { id: 122, name: "Fiery Italian" },
  { id: 123, name: "Girl Power" },
  { id: 124, name: "Valley Girl" },
  { id: 125, name: "Daddy's Girl" },
  { id: 126, name: "Equality Fighter" },
  { id: 127, name: "Misogynist" },
  { id: 128, name: "Foreign Royalty" },
  { id: 129, name: "Royalty" },
  { id: 130, name: "Harsh German" },
  { id: 131, name: "Witch" },
  { id: 132, name: "Magician" },
  { id: 133, name: "Boy Band" },
  { id: 134, name: "Law Enforcer" },
  { id: 135, name: "Corrupt Law Officer" },
  { id: 136, name: "Voodoo" },
  { id: 137, name: "Pimp" },
  { id: 138, name: "Evil Pimp" },
  { id: 139, name: "City Slicker" },
  { id: 140, name: "Evil Dentist" },
  { id: 141, name: "Masochist" },
  { id: 142, name: "Lawyer" },
  { id: 143, name: "Conman" },
  { id: 144, name: "Mafia" },
  { id: 145, name: "Triad" },
  { id: 146, name: "Informer" },
  { id: 147, name: "Rasta" },
  { id: 148, name: "Racist" },
  { id: 149, name: "Religious Zealot" },
  { id: 150, name: "Cult Leader" },
  { id: 151, name: "Pyromaniac" },
  { id: 152, name: "All-American" },
  { id: 153, name: "Dual-Sport Superstar" },
  { id: 154, name: "Manic Depressive" },
  { id: 155, name: "Knight" },
  { id: 156, name: "Evil Knight" },
  { id: 157, name: "Street Fighter" },
  { id: 158, name: "Sumo" },
  { id: 159, name: "Sports Agent" },
  { id: 160, name: "The Ryland Effect" },
  { id: 161, name: "Pretentious Artist" },
  { id: 162, name: "Dance" },
  { id: 163, name: "Secretary" },
  { id: 164, name: "Staff Member" },
  { id: 165, name: "Guru" },
  { id: 166, name: "Sucka" },
  { id: 167, name: "Hillbilly" },
  { id: 168, name: "Evil Referee" },
  { id: 169, name: "Servant" },
  { id: 170, name: "That 70's Guy" },
  { id: 171, name: "That 80's Guy" },
  { id: 172, name: "Grizzled Veteran" },
  { id: 173, name: "Fitness Instructor" },
  { id: 174, name: "White Witch" },
  { id: 175, name: "Postal Worker" },
  { id: 176, name: "Clown" },
  { id: 177, name: "Evil Clown" },
  { id: 178, name: "Streaker" },
  { id: 179, name: "Country Singer" },
  { id: 180, name: "Whole Damn Show" },
  { id: 181, name: "Show Stealer" },
  { id: 182, name: "Man Beast" },
  { id: 183, name: "Angry Minority" },
  { id: 184, name: "Vampire" },
  { id: 185, name: "Obsessed Fan" },
  { id: 186, name: "Pirate" },
  { id: 187, name: "Sheik" },
  { id: 188, name: "Rock Star" },
  { id: 189, name: "Ice Man" },
  { id: 190, name: "Bully" },
  { id: 191, name: "Paper Boy" },
  { id: 192, name: "Convict" },
  { id: 193, name: "Bum" },
  { id: 194, name: "Commissioner" },
  { id: 195, name: "People's Boss" },
  { id: 196, name: "Luchadore" },
  { id: 197, name: "Biker" },
  { id: 198, name: "Mountie" },
  { id: 199, name: "Family Guy" },
  { id: 200, name: "Nerd" },
  { id: 201, name: "Evolution" },
  { id: 202, name: "Adult Film Star" },
  { id: 203, name: "Shark Boy" },
  { id: 204, name: "Clean Cut" },
];

export const GIMMICK_NAME_BY_ID: Record<number, string> = Object.fromEntries(GIMMICKS.map(g => [g.id, g.name]));
